### ISSUE TITLE
Test flicker

### ISSUE THREAD

**Issue by Floppy** [openpolitics/votebot#169]
failing seed: 47667
passing seed: 27095

**Comment by Floppy** [comment]
In webhook spec.

```
  1) webhook POST / should parse github issue comments correctly
     Failure/Error: expect(UpdateProposalJob).to have_been_enqueued.with(32)

     ActiveJob::DeserializationError:
       Error while trying to deserialize arguments: Couldn't find Proposal with 'id'=1
     # ./spec/integration/webhook_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:119:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ActiveRecord::RecordNotFound:
     #   Couldn't find Proposal with 'id'=1
     #   ./spec/integration/webhook_spec.rb:18:in `block (2 levels) in <top (required)>'
```
